# Generated by Django 5.1.5 on 2025-04-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vid", models.TextField()),
                ("last_name", models.TextField()),
                ("first_name", models.TextField()),
                ("street_number", models.IntegerField()),
                ("street_name", models.TextField()),
                ("apartment_number", models.TextField(blank=True)),
                ("zip_code", models.IntegerField()),
                ("dob", models.DateField()),
                ("registration_date", models.DateField()),
                ("party", models.CharField(max_length=2)),
                ("precinct", models.IntegerField()),
                ("v20_state", models.BooleanField()),
                ("v21_town", models.BooleanField()),
                ("v21_primary", models.BooleanField()),
                ("v22_general", models.BooleanField()),
                ("v23_town", models.BooleanField()),
                ("voter_score", models.IntegerField()),
            ],
        ),
    ]
