# Generated by Django 5.1.5 on 2025-04-15 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('credit_score', models.IntegerField(blank=True)),
                ('license_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('years_working', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.TextField()),
                ('make', models.TextField()),
                ('model', models.TextField()),
                ('year', models.TextField()),
                ('body_type', models.TextField()),
                ('engine_size', models.IntegerField()),
                ('mpg', models.IntegerField()),
                ('msrp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.customer')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.salesperson')),
            ],
        ),
        migrations.CreateModel(
            name='SalespersonReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.customer')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.salesperson')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='interested_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.vehicle'),
        ),
        migrations.CreateModel(
            name='VehicleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField()),
                ('car_image', models.ImageField(blank=True, upload_to='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.vehicle')),
            ],
        ),
    ]
