# Generated by Django 5.2 on 2025-04-18 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='interested_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.vehicle'),
        ),
    ]
