# Generated by Django 5.2 on 2025-04-29 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_customer_user_salesperson_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespersonreview',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='vehiclereview',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
