# Generated by Django 5.2 on 2025-04-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_salespersonreview_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='isSold',
            field=models.BooleanField(default=False),
        ),
    ]
