# Generated by Django 5.1.5 on 2025-05-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_vehicle_issold'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleReview',
        ),
    ]
